package exceldb.model;

public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.FILE_NAME
     *
     * @return the value of HISTORY.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.FILE_NAME
     *
     * @param fileName the value for HISTORY.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}