package exceldb.dao;

import exceldb.model.Authentication;
import exceldb.model.AuthenticationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int countByExample(AuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int deleteByExample(AuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int insert(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int insertSelective(Authentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    List<Authentication> selectByExample(AuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Authentication record, @Param("example") AuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHENTICATION
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Authentication record, @Param("example") AuthenticationExample example);
}