package exceldb.dao;

import exceldb.model.Folder;
import exceldb.model.FolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int countByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int deleteByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int insert(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int insertSelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    List<Folder> selectByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Folder record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOLDER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Folder record, @Param("example") FolderExample example);
}