package exceldb.dao;

import exceldb.model.History;
import exceldb.model.HistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int countByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int deleteByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int insert(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int insertSelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    List<History> selectByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") History record, @Param("example") HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") History record, @Param("example") HistoryExample example);
}