package exceldb.dao;

import exceldb.model.Pii;
import exceldb.model.PiiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PiiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int countByExample(PiiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int deleteByExample(PiiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int insert(Pii record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int insertSelective(Pii record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    List<Pii> selectByExample(PiiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pii record, @Param("example") PiiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PII
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pii record, @Param("example") PiiExample example);
}