package exceldb.model;

public class Authentication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATION.ROLE
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHENTICATION.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATION.ROLE
     *
     * @return the value of AUTHENTICATION.ROLE
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATION.ROLE
     *
     * @param role the value for AUTHENTICATION.ROLE
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHENTICATION.PASSWORD
     *
     * @return the value of AUTHENTICATION.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHENTICATION.PASSWORD
     *
     * @param password the value for AUTHENTICATION.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}