package exceldb.model;

public class Folder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOLDER.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOLDER.PATH
     *
     * @return the value of FOLDER.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOLDER.PATH
     *
     * @param path the value for FOLDER.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}