package exceldb.model;

public class Pii {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.LOCAL_ID
     *
     * @mbggenerated
     */
    private String localId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.GUID
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.MRN
     *
     * @mbggenerated
     */
    private String mrn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.身份證字號
     *
     * @mbggenerated
     */
    private String 身份證字號;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.姓氏
     *
     * @mbggenerated
     */
    private String 姓氏;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.名字
     *
     * @mbggenerated
     */
    private String 名字;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.出生月
     *
     * @mbggenerated
     */
    private String 出生月;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.出生日
     *
     * @mbggenerated
     */
    private String 出生日;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.出生年
     *
     * @mbggenerated
     */
    private String 出生年;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.聯絡電話
     *
     * @mbggenerated
     */
    private String 聯絡電話;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.性別
     *
     * @mbggenerated
     */
    private String 性別;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.收案醫師
     *
     * @mbggenerated
     */
    private String 收案醫師;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PII.收案醫院名稱
     *
     * @mbggenerated
     */
    private String 收案醫院名稱;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.LOCAL_ID
     *
     * @return the value of PII.LOCAL_ID
     *
     * @mbggenerated
     */
    public String getLocalId() {
        return localId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.LOCAL_ID
     *
     * @param localId the value for PII.LOCAL_ID
     *
     * @mbggenerated
     */
    public void setLocalId(String localId) {
        this.localId = localId == null ? null : localId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.GUID
     *
     * @return the value of PII.GUID
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.GUID
     *
     * @param guid the value for PII.GUID
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.MRN
     *
     * @return the value of PII.MRN
     *
     * @mbggenerated
     */
    public String getMrn() {
        return mrn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.MRN
     *
     * @param mrn the value for PII.MRN
     *
     * @mbggenerated
     */
    public void setMrn(String mrn) {
        this.mrn = mrn == null ? null : mrn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.身份證字號
     *
     * @return the value of PII.身份證字號
     *
     * @mbggenerated
     */
    public String get身份證字號() {
        return 身份證字號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.身份證字號
     *
     * @param 身份證字號 the value for PII.身份證字號
     *
     * @mbggenerated
     */
    public void set身份證字號(String 身份證字號) {
        this.身份證字號 = 身份證字號 == null ? null : 身份證字號.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.姓氏
     *
     * @return the value of PII.姓氏
     *
     * @mbggenerated
     */
    public String get姓氏() {
        return 姓氏;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.姓氏
     *
     * @param 姓氏 the value for PII.姓氏
     *
     * @mbggenerated
     */
    public void set姓氏(String 姓氏) {
        this.姓氏 = 姓氏 == null ? null : 姓氏.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.名字
     *
     * @return the value of PII.名字
     *
     * @mbggenerated
     */
    public String get名字() {
        return 名字;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.名字
     *
     * @param 名字 the value for PII.名字
     *
     * @mbggenerated
     */
    public void set名字(String 名字) {
        this.名字 = 名字 == null ? null : 名字.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.出生月
     *
     * @return the value of PII.出生月
     *
     * @mbggenerated
     */
    public String get出生月() {
        return 出生月;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.出生月
     *
     * @param 出生月 the value for PII.出生月
     *
     * @mbggenerated
     */
    public void set出生月(String 出生月) {
        this.出生月 = 出生月 == null ? null : 出生月.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.出生日
     *
     * @return the value of PII.出生日
     *
     * @mbggenerated
     */
    public String get出生日() {
        return 出生日;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.出生日
     *
     * @param 出生日 the value for PII.出生日
     *
     * @mbggenerated
     */
    public void set出生日(String 出生日) {
        this.出生日 = 出生日 == null ? null : 出生日.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.出生年
     *
     * @return the value of PII.出生年
     *
     * @mbggenerated
     */
    public String get出生年() {
        return 出生年;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.出生年
     *
     * @param 出生年 the value for PII.出生年
     *
     * @mbggenerated
     */
    public void set出生年(String 出生年) {
        this.出生年 = 出生年 == null ? null : 出生年.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.聯絡電話
     *
     * @return the value of PII.聯絡電話
     *
     * @mbggenerated
     */
    public String get聯絡電話() {
        return 聯絡電話;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.聯絡電話
     *
     * @param 聯絡電話 the value for PII.聯絡電話
     *
     * @mbggenerated
     */
    public void set聯絡電話(String 聯絡電話) {
        this.聯絡電話 = 聯絡電話 == null ? null : 聯絡電話.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.性別
     *
     * @return the value of PII.性別
     *
     * @mbggenerated
     */
    public String get性別() {
        return 性別;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.性別
     *
     * @param 性別 the value for PII.性別
     *
     * @mbggenerated
     */
    public void set性別(String 性別) {
        this.性別 = 性別 == null ? null : 性別.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.收案醫師
     *
     * @return the value of PII.收案醫師
     *
     * @mbggenerated
     */
    public String get收案醫師() {
        return 收案醫師;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.收案醫師
     *
     * @param 收案醫師 the value for PII.收案醫師
     *
     * @mbggenerated
     */
    public void set收案醫師(String 收案醫師) {
        this.收案醫師 = 收案醫師 == null ? null : 收案醫師.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PII.收案醫院名稱
     *
     * @return the value of PII.收案醫院名稱
     *
     * @mbggenerated
     */
    public String get收案醫院名稱() {
        return 收案醫院名稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PII.收案醫院名稱
     *
     * @param 收案醫院名稱 the value for PII.收案醫院名稱
     *
     * @mbggenerated
     */
    public void set收案醫院名稱(String 收案醫院名稱) {
        this.收案醫院名稱 = 收案醫院名稱 == null ? null : 收案醫院名稱.trim();
    }
}